In [52]:
import csv
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [53]:
bc = "companydata.csv"
df = pd.read_csv(bc, header = 0)
df

X1        X2         X3       X4       X5         X6         X7  \
0       0.20055   0.37951    0.39641   2.0472   32.351    0.38825    0.24976   
1       0.20912   0.49988    0.47225   1.9447   14.786          0    0.25834   
2       0.24866   0.69592    0.26713   1.5548  -1.1523          0    0.30906   
3      0.081483   0.30734    0.45879   2.4928   51.952    0.14988   0.092704   
4       0.18732   0.61323     0.2296   1.4063  -7.3128    0.18732    0.18732   
5       0.22822   0.49794    0.35969   1.7502  -47.717          0    0.28139   
6       0.11109   0.64744    0.28971   1.4705   2.5349          0    0.11109   
7       0.53232  0.027059    0.70554   53.954   299.58          0     0.6524   
8       0.00902   0.63202   0.053735   1.1263  -37.842          0   0.014434   
9       0.12408   0.83837    0.14204   1.1694  -91.883          0    0.15328   
10      0.24001   0.44355    0.18835     1.44  -21.165    -0.9319    0.24001   
11    -0.027117   0.11148    0.11989   2.0754  -31.643  -0.084883    -0.0243   
12      0.26669   0.34994    0.61147   3.0243   43.087    0.55983    0.33207   
13     0.067731   0.19885   0.081562   2.9576   90.606    0.21265   0.078063   
14    -0.029182   0.21131    0.45264   7.5746   57.844   0.010387  -0.034653   
15    -0.033801     1.154   -0.20599   0.8215  -74.451   -0.10413  -0.033801   
16      0.27053   0.29913     0.4687   2.5669   73.395    0.72793    0.33619   
17     0.028084   0.24231    0.43224   3.0128   47.935   0.021598   0.039729   
18      0.20393   0.56037    0.13495   1.2408    3.158          0    0.24291   
19      0.20876    0.4965    0.42548    2.019   38.934   0.005436    0.25619   
20      0.11119   0.63174    0.24796        2   58.154    0.24347    0.13909   
21     -0.30505    1.2523   -0.29222  0.71426  -214.91   -0.30505   -0.30505   
22      0.12709    0.5305    0.38069   1.7198  -27.618          0    0.15611   
23      0.12624   0.66286    0.21916   1.3553   21.588   0.020227    0.15633   
24      0.29264   0.29252    0.34415    2.327   108.07          0    0.36131   
25     0.079997   0.23967    0.32124   2.4739   8.1087    0.20743   0.069715   
26      0.20817    0.6024    0.47935   2.1883   69.659          0    0.25911   
27      0.26345   0.14318    0.61965   5.3277   198.95    0.55971    0.32142   
28    -0.054623   0.92857  -0.026927  0.94263  -87.724  -0.054623  -0.054623   
29     -0.35884    1.1171   -0.46577  0.46115  -152.21    -1.1752   -0.35884   
...         ...       ...        ...      ...      ...        ...        ...   
6997   0.003802   0.14144    0.44904   4.1748   60.896   0.003802  -0.004791   
6998  -0.018516   0.32886   0.069952    1.257  -29.298          0  -0.018781   
6999    0.02283   0.71132  -0.060759   0.6912  -14.081  -0.048958   0.024774   
7000  -0.000153   0.50582   -0.42127  0.15367  -883.03  -0.000153  -0.004183   
7001   -0.28971    1.1874   -0.46532  0.53814  -223.28   -0.28971   -0.28971   
7002   0.009313   0.61761   -0.22233  0.60119   -62.63          0   0.014544   
7003    0.16773   0.77389    0.16663   1.2414  -28.039          0    0.21742   
7004   -0.33033   0.93266   -0.47693  0.48863  -350.83   -0.33033   -0.33033   
7005    0.04608  0.003824    0.99618    261.5   174.33          0    0.04608   
7006    0.13331   0.16451    0.40084   3.4366   2.8373          0    0.16928   
7007   0.038665  0.071884    0.48884   7.8004   221.01   0.038665   0.045892   
7008   0.001091    0.8516   0.003463   1.0086  -44.467   0.086248   0.001091   
7009  -0.091442    0.7055  -0.047216  0.92568  -7.2952          0  -0.090374   
7010    0.13809    3.3357     -2.364  0.29128  -88.382    -3.3963    0.13809   
7011   0.098271    0.8333   0.000426   1.0005  -43.191          0    0.12838   
7012   0.006404   0.67477  -0.008438  0.98668  -45.599          0   0.009958   
7013   0.037953   0.12239    0.23084    2.886   19.581   0.037953   0.040082   
7014    0.16117  0.072135    0.63649   12.025    178.9          0    0.19986   
7015   0.0194

In [54]:
test = df.replace('?', np.NaN)
test

X1        X2         X3       X4       X5         X6         X7  \
0       0.20055   0.37951    0.39641   2.0472   32.351    0.38825    0.24976   
1       0.20912   0.49988    0.47225   1.9447   14.786          0    0.25834   
2       0.24866   0.69592    0.26713   1.5548  -1.1523          0    0.30906   
3      0.081483   0.30734    0.45879   2.4928   51.952    0.14988   0.092704   
4       0.18732   0.61323     0.2296   1.4063  -7.3128    0.18732    0.18732   
5       0.22822   0.49794    0.35969   1.7502  -47.717          0    0.28139   
6       0.11109   0.64744    0.28971   1.4705   2.5349          0    0.11109   
7       0.53232  0.027059    0.70554   53.954   299.58          0     0.6524   
8       0.00902   0.63202   0.053735   1.1263  -37.842          0   0.014434   
9       0.12408   0.83837    0.14204   1.1694  -91.883          0    0.15328   
10      0.24001   0.44355    0.18835     1.44  -21.165    -0.9319    0.24001   
11    -0.027117   0.11148    0.11989   2.0754  -31.643  -0.084883    -0.0243   
12      0.26669   0.34994    0.61147   3.0243   43.087    0.55983    0.33207   
13     0.067731   0.19885   0.081562   2.9576   90.606    0.21265   0.078063   
14    -0.029182   0.21131    0.45264   7.5746   57.844   0.010387  -0.034653   
15    -0.033801     1.154   -0.20599   0.8215  -74.451   -0.10413  -0.033801   
16      0.27053   0.29913     0.4687   2.5669   73.395    0.72793    0.33619   
17     0.028084   0.24231    0.43224   3.0128   47.935   0.021598   0.039729   
18      0.20393   0.56037    0.13495   1.2408    3.158          0    0.24291   
19      0.20876    0.4965    0.42548    2.019   38.934   0.005436    0.25619   
20      0.11119   0.63174    0.24796        2   58.154    0.24347    0.13909   
21     -0.30505    1.2523   -0.29222  0.71426  -214.91   -0.30505   -0.30505   
22      0.12709    0.5305    0.38069   1.7198  -27.618          0    0.15611   
23      0.12624   0.66286    0.21916   1.3553   21.588   0.020227    0.15633   
24      0.29264   0.29252    0.34415    2.327   108.07          0    0.36131   
25     0.079997   0.23967    0.32124   2.4739   8.1087    0.20743   0.069715   
26      0.20817    0.6024    0.47935   2.1883   69.659          0    0.25911   
27      0.26345   0.14318    0.61965   5.3277   198.95    0.55971    0.32142   
28    -0.054623   0.92857  -0.026927  0.94263  -87.724  -0.054623  -0.054623   
29     -0.35884    1.1171   -0.46577  0.46115  -152.21    -1.1752   -0.35884   
...         ...       ...        ...      ...      ...        ...        ...   
6997   0.003802   0.14144    0.44904   4.1748   60.896   0.003802  -0.004791   
6998  -0.018516   0.32886   0.069952    1.257  -29.298          0  -0.018781   
6999    0.02283   0.71132  -0.060759   0.6912  -14.081  -0.048958   0.024774   
7000  -0.000153   0.50582   -0.42127  0.15367  -883.03  -0.000153  -0.004183   
7001   -0.28971    1.1874   -0.46532  0.53814  -223.28   -0.28971   -0.28971   
7002   0.009313   0.61761   -0.22233  0.60119   -62.63          0   0.014544   
7003    0.16773   0.77389    0.16663   1.2414  -28.039          0    0.21742   
7004   -0.33033   0.93266   -0.47693  0.48863  -350.83   -0.33033   -0.33033   
7005    0.04608  0.003824    0.99618    261.5   174.33          0    0.04608   
7006    0.13331   0.16451    0.40084   3.4366   2.8373          0    0.16928   
7007   0.038665  0.071884    0.48884   7.8004   221.01   0.038665   0.045892   
7008   0.001091    0.8516   0.003463   1.0086  -44.467   0.086248   0.001091   
7009  -0.091442    0.7055  -0.047216  0.92568  -7.2952          0  -0.090374   
7010    0.13809    3.3357     -2.364  0.29128  -88.382    -3.3963    0.13809   
7011   0.098271    0.8333   0.000426   1.0005  -43.191          0    0.12838   
7012   0.006404   0.67477  -0.008438  0.98668  -45.599          0   0.009958   
7013   0.037953   0.12239    0.23084    2.886   19.581   0.037953   0.040082   
7014    0.16117  0.072135    0.63649   12.025    178.9          0    0.19986   
7015   0.0194

In [55]:
test2 = test.dropna()

In [56]:
#1,35,5,34,39,47,58,56,42 1-->0.20 regression
#tree classifier
dfsub=test2[['X1','X35','X5','X34','X39','X47', 'X58','X56','X42','X65']]

In [57]:
dfsub

X1        X35       X5        X34       X39      X47      X58  \
0       0.20055    0.21402   32.351    0.56393  0.128040   49.394  0.87804   
8       0.00902    0.24013  -37.842     1.7697  0.180110   43.654  0.84165   
12      0.26669    0.30471   43.087    0.87075  0.105480   43.023  0.88750   
13     0.067731    0.05373   90.606    0.27021  0.212760   55.868  0.79556   
14    -0.029182  -0.050624   57.844   -0.23957 -0.064076   107.89  0.97644   
17     0.028084   0.054953   47.935    0.22679  0.029084   36.686  0.98763   
25     0.079997   0.084917   8.1087     0.3543  0.048485   62.571  0.94730   
29     -0.35884    -0.1916  -152.21   -0.17151 -0.119890   39.499  1.02930   
30      0.10248    0.13335   -2.921    0.45993  0.084870   19.046  0.92548   
31       0.1409    0.12079  -11.094    0.15986  0.047064   61.692  0.95167   
33     0.001222  -0.007323  -44.797  -0.013789 -0.004822   88.458  1.00920   
34     0.013079  -0.018598   -58.08  -0.024522 -0.007406    49.32  1.00700   
35     0.099873    0.10364  -1.2568    0.18051  0.067762   19.414  0.92991   
42     0.033901   0.048431  -59.217    0.20142  0.070389   3.6163  0.93176   
49      0.17203    0.23694   3.4455    0.42074  0.116960   58.697  0.88429   
52     -0.00175   0.004289   -29.76   0.008537  0.010200  0.81039  0.95238   
54      0.14813    0.17353   58.226    0.34397  0.094728   24.594  0.91942   
55      0.21043    0.24265   26.737    0.75993  0.090151   9.3205  0.96299   
56      0.19437    0.26231   44.573    0.53043  0.231810   5.2837  0.89990   
71      0.06773   0.094205   24.998    0.49498  0.054712   33.038  0.94243   
73     0.064812   0.086115  -27.265    0.21672  0.064480   88.016  0.91678   
77     0.086734    0.15464   6.4534     2.2653  0.161690   9.5976  0.83383   
80     0.087366    0.12126  -7.1206    0.35774  0.109060   113.29  0.88934   
83     0.077604    0.38315    44.75     2.2538  0.366390     89.4  0.64396   
84      0.24737    0.15888  -33.963    0.35869  0.095101    30.81  0.90465   
85     0.082955    0.10992   6.5078    0.18576  0.065751   58.801  0.92805   
88     0.026461    0.06946   -14.73    0.10743  0.027869   46.355  0.96427   
90     0.007744   0.012961  -81.363   0.017129  0.013316   73.023  0.98259   
92      0.39616    0.48064   190.13     2.5352  0.518620   90.015  0.95585   
101   -0.030391  -0.030801  -100.72  -0.020514 -0.014434   45.258  1.01270   
...         ...        ...      ...        ...       ...      ...      ...   
6766    0.17651    0.20244  -98.676     2.1619  0.107650   51.529  0.80803   
6778   -0.14212  -0.087692  -180.11     1.2594 -0.087077   158.65  0.99410   
6784   0.029722   0.042873   -27.55     2.7328  0.019967   53.838  0.97279   
6788   0.023079   0.053235  -37.712      1.842  0.046457   47.725  0.92159   
6791   0.007599   0.028624      -82    0.31918  0.102200   47.023  0.78308   
6826   0.005924   0.066441  -171.77     0.8362  0.080943   210.89  0.88167   
6856    0.02019    0.12803  -61.716     3.2717  0.042514   64.287  0.98567   
6872   0.068702    0.13413  -13.051     2.5187  0.064449   63.479  0.91419   
6876  -0.009092   0.000641  -8.5706     4.1884  0.000174   39.956  0.99287   
6881   0.000493  -0.005938  -22.197     1.9764 -0.007810   72.293  0.91345   
6891    0.14186    0.23821   8.9011     4.4753  0.091738   28.597  0.91452   
6894  -0.029387   -0.02776   6.3828     2.3138 -0.018893   66.979  1.00430   
6924          0    0.17757   75.857     1.7817  0.151200   114.28  0.62301   
6931   0.013551   0.077797  -71.309     2.3124  0.038374   75.971  0.96854   
6936    0.11854   0.014343  -12.926      13.02  0.002518   14.938  0.97430   
6947    0.18835    0.21995   36.159     5.1727  0.090248   22.247  0.90284   
6949   0.023532   0.054286  -68.569     2.9611  0.023858   48.182  0.97573   
6951   0.012653    0.06328  -34.061     3.8062  0.024851   28.427  0.98456   
6953   0.048529   0.076413   -17.57     5.9183  0.015825   2.2903  0.98569   
6954  -0.008735   0.016633  -72.221

In [58]:
from sklearn.model_selection import train_test_split

In [59]:
X=test2.drop('X65',axis=1)

In [60]:
y=test2['X65']

In [61]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [62]:
from sklearn.tree import DecisionTreeClassifier

In [63]:
dtree = DecisionTreeClassifier(criterion='entropy')

In [64]:
dtree.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [65]:
predictions = dtree.predict(X_test)

In [66]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import metrics

In [67]:
print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))
print('\n')
print(metrics.accuracy_score(y_test,predictions))

[[629   5]
 [  4   1]]


             precision    recall  f1-score   support

          0       0.99      0.99      0.99       634
          1       0.17      0.20      0.18         5

avg / total       0.99      0.99      0.99       639



0.985915492958


In [68]:
#regression 

In [69]:
from sklearn.tree import DecisionTreeRegressor

In [70]:
dtree = DecisionTreeRegressor()

In [71]:
dtree.fit(X_train,y_train)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best')

In [72]:
predictions = dtree.predict(X_test)

In [73]:
from sklearn.metrics import classification_report, confusion_matrix

In [74]:
print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

[[628   6]
 [  5   0]]


             precision    recall  f1-score   support

          0       0.99      0.99      0.99       634
          1       0.00      0.00      0.00         5

avg / total       0.98      0.98      0.98       639



In [75]:
#random forest

In [76]:
from sklearn.ensemble import RandomForestClassifier

In [77]:
model=RandomForestClassifier(n_estimators=10, max_depth=None,min_samples_split=2, random_state=0)

In [78]:
model.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [79]:
predictions = model.predict(X_test)

In [80]:
from sklearn.metrics import classification_report, confusion_matrix

In [81]:
print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))


[[633   1]
 [  5   0]]


             precision    recall  f1-score   support

          0       0.99      1.00      1.00       634
          1       0.00      0.00      0.00         5

avg / total       0.98      0.99      0.99       639



In [82]:
#knn

In [83]:
from sklearn.neighbors.nearest_centroid import NearestCentroid

In [84]:
model=NearestCentroid()

In [85]:
model.fit(X_train,y_train)

NearestCentroid(metric='euclidean', shrink_threshold=None)

In [86]:
predictions = model.predict(X_test)

In [87]:
from sklearn.metrics import classification_report, confusion_matrix

In [88]:
print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

[[543  91]
 [  4   1]]


             precision    recall  f1-score   support

          0       0.99      0.86      0.92       634
          1       0.01      0.20      0.02         5

avg / total       0.99      0.85      0.91       639



In [89]:
#Probabilistic

In [90]:
from sklearn.naive_bayes import GaussianNB

In [91]:
model = GaussianNB()

In [92]:
model.fit(X_train,y_train)

GaussianNB(priors=None)

In [93]:
predictions = model.predict(X_test)

In [94]:
from sklearn.metrics import classification_report, confusion_matrix

In [95]:
print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

[[ 99 535]
 [  0   5]]


             precision    recall  f1-score   support

          0       1.00      0.16      0.27       634
          1       0.01      1.00      0.02         5

avg / total       0.99      0.16      0.27       639



In [96]:
#SVM's

In [97]:
from sklearn.svm import SVC

In [98]:
model = SVC()

In [99]:
model.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [100]:
predictions = model.predict(X_test)

In [101]:
from sklearn.metrics import classification_report, confusion_matrix

In [102]:
print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

[[634   0]
 [  5   0]]


             precision    recall  f1-score   support

          0       0.99      1.00      1.00       634
          1       0.00      0.00      0.00         5

avg / total       0.98      0.99      0.99       639



/home/ven/Venenv/local/lib/python2.7/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [104]:
#gotta change dem objects to floats man
test.dtypes.eq(object)
c = test.columns[test.dtypes.eq(object)]
test[c] = test[c].apply(pd.to_numeric, errors='coerce', axis=0)
test.dtypes 


X1     float64
X2     float64
X3     float64
X4     float64
X5     float64
X6     float64
X7     float64
X8     float64
X9     float64
X10    float64
X11    float64
X12    float64
X13    float64
X14    float64
X15    float64
X16    float64
X17    float64
X18    float64
X19    float64
X20    float64
X21    float64
X22    float64
X23    float64
X24    float64
X25    float64
X26    float64
X27    float64
X28    float64
X29    float64
X30    float64
        ...   
X36    float64
X37    float64
X38    float64
X39    float64
X40    float64
X41    float64
X42    float64
X43    float64
X44    float64
X45    float64
X46    float64
X47    float64
X48    float64
X49    float64
X50    float64
X51    float64
X52    float64
X53    float64
X54    float64
X55    float64
X56    float64
X57    float64
X58    float64
X59    float64
X60    float64
X61    float64
X62    float64
X63    float64
X64    float64
X65      int64
Length: 65, dtype: object

In [143]:
#filling missing values instead of deleting them
test5=test.fillna(test.mean())


In [144]:
test5

X1        X2        X3         X4        X5        X6        X7  \
0     0.200550  0.379510  0.396410    2.04720   32.3510  0.388250  0.249760   
1     0.209120  0.499880  0.472250    1.94470   14.7860  0.000000  0.258340   
2     0.248660  0.695920  0.267130    1.55480   -1.1523  0.000000  0.309060   
3     0.081483  0.307340  0.458790    2.49280   51.9520  0.149880  0.092704   
4     0.187320  0.613230  0.229600    1.40630   -7.3128  0.187320  0.187320   
5     0.228220  0.497940  0.359690    1.75020  -47.7170  0.000000  0.281390   
6     0.111090  0.647440  0.289710    1.47050    2.5349  0.000000  0.111090   
7     0.532320  0.027059  0.705540   53.95400  299.5800  0.000000  0.652400   
8     0.009020  0.632020  0.053735    1.12630  -37.8420  0.000000  0.014434   
9     0.124080  0.838370  0.142040    1.16940  -91.8830  0.000000  0.153280   
10    0.240010  0.443550  0.188350    1.44000  -21.1650 -0.931900  0.240010   
11   -0.027117  0.111480  0.119890    2.07540  -31.6430 -0.084883 -0.024300   
12    0.266690  0.349940  0.611470    3.02430   43.0870  0.559830  0.332070   
13    0.067731  0.198850  0.081562    2.95760   90.6060  0.212650  0.078063   
14   -0.029182  0.211310  0.452640    7.57460   57.8440  0.010387 -0.034653   
15   -0.033801  1.154000 -0.205990    0.82150  -74.4510 -0.104130 -0.033801   
16    0.270530  0.299130  0.468700    2.56690   73.3950  0.727930  0.336190   
17    0.028084  0.242310  0.432240    3.01280   47.9350  0.021598  0.039729   
18    0.203930  0.560370  0.134950    1.24080    3.1580  0.000000  0.242910   
19    0.208760  0.496500  0.425480    2.01900   38.9340  0.005436  0.256190   
20    0.111190  0.631740  0.247960    2.00000   58.1540  0.243470  0.139090   
21   -0.305050  1.252300 -0.292220    0.71426 -214.9100 -0.305050 -0.305050   
22    0.127090  0.530500  0.380690    1.71980  -27.6180  0.000000  0.156110   
23    0.126240  0.662860  0.219160    1.35530   21.5880  0.020227  0.156330   
24    0.292640  0.292520  0.344150    2.32700  108.0700  0.000000  0.361310   
25    0.079997  0.239670  0.321240    2.47390    8.1087  0.207430  0.069715   
26    0.208170  0.602400  0.479350    2.18830   69.6590  0.000000  0.259110   
27    0.263450  0.143180  0.619650    5.32770  198.9500  0.559710  0.321420   
28   -0.054623  0.928570 -0.026927    0.94263  -87.7240 -0.054623 -0.054623   
29   -0.358840  1.117100 -0.465770    0.46115 -152.2100 -1.175200 -0.358840   
...        ...       ...       ...        ...       ...       ...       ...   
6997  0.003802  0.141440  0.449040    4.17480   60.8960  0.003802 -0.004791   
6998 -0.018516  0.328860  0.069952    1.25700  -29.2980  0.000000 -0.018781   
6999  0.022830  0.711320 -0.060759    0.69120  -14.0810 -0.048958  0.024774   
7000 -0.000153  0.505820 -0.421270    0.15367 -883.0300 -0.000153 -0.004183   
7001 -0.289710  1.187400 -0.465320    0.53814 -223.2800 -0.289710 -0.289710   
7002  0.009313  0.617610 -0.222330    0.60119  -62.6300  0.000000  0.014544   
7003  0.167730  0.773890  0.166630    1.24140  -28.0390  0.000000  0.217420   
7004 -0.330330  0.932660 -0.476930    0.48863 -350.8300 -0.330330 -0.330330   
7005  0.046080  0.003824  0.996180  261.50000  174.3300  0.000000  0.046080   
7006  0.133310  0.164510  0.400840    3.43660    2.8373  0.000000  0.169280   
7007  0.038665  0.071884  0.488840    7.80040  221.0100  0.038665  0.045892   
7008  0.001091  0.851600  0.003463    1.00860  -44.4670  0.086248  0.001091   
7009 -0.091442  0.705500 -0.047216    0.92568   -7.2952  0.000000 -0.090374   
7010  0.138090  3.335700 -2.364000    0.29128  -88.3820 -3.396300  0.138090   
7011  0.098271  0.833300  0.000426    1.00050  -43.1910  0.000000  0.128380   
7012  0.006404  0.674770 -0.008438    0.98668  -45.5990  0.000000  0.009958   
7013  0.037953  0.122390  0.230840    2.88600   19.5810  0.037953  0.040082   
7014  0.161170  0.072135  0.636490   12.02500  178.9000  0.000000  0.199860   
7015  0.019432  0.616330  0.057718    1.10620 -162.8800  0.019