In [178]:
import csv
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [179]:
bc = "companydata.csv"
df = pd.read_csv(bc, header = 0)
df

X1        X2         X3       X4       X5         X6         X7  \
0       0.20055   0.37951    0.39641   2.0472   32.351    0.38825    0.24976   
1       0.20912   0.49988    0.47225   1.9447   14.786          0    0.25834   
2       0.24866   0.69592    0.26713   1.5548  -1.1523          0    0.30906   
3      0.081483   0.30734    0.45879   2.4928   51.952    0.14988   0.092704   
4       0.18732   0.61323     0.2296   1.4063  -7.3128    0.18732    0.18732   
5       0.22822   0.49794    0.35969   1.7502  -47.717          0    0.28139   
6       0.11109   0.64744    0.28971   1.4705   2.5349          0    0.11109   
7       0.53232  0.027059    0.70554   53.954   299.58          0     0.6524   
8       0.00902   0.63202   0.053735   1.1263  -37.842          0   0.014434   
9       0.12408   0.83837    0.14204   1.1694  -91.883          0    0.15328   
10      0.24001   0.44355    0.18835     1.44  -21.165    -0.9319    0.24001   
11    -0.027117   0.11148    0.11989   2.0754  -31.643  -0.084883    -0.0243   
12      0.26669   0.34994    0.61147   3.0243   43.087    0.55983    0.33207   
13     0.067731   0.19885   0.081562   2.9576   90.606    0.21265   0.078063   
14    -0.029182   0.21131    0.45264   7.5746   57.844   0.010387  -0.034653   
15    -0.033801     1.154   -0.20599   0.8215  -74.451   -0.10413  -0.033801   
16      0.27053   0.29913     0.4687   2.5669   73.395    0.72793    0.33619   
17     0.028084   0.24231    0.43224   3.0128   47.935   0.021598   0.039729   
18      0.20393   0.56037    0.13495   1.2408    3.158          0    0.24291   
19      0.20876    0.4965    0.42548    2.019   38.934   0.005436    0.25619   
20      0.11119   0.63174    0.24796        2   58.154    0.24347    0.13909   
21     -0.30505    1.2523   -0.29222  0.71426  -214.91   -0.30505   -0.30505   
22      0.12709    0.5305    0.38069   1.7198  -27.618          0    0.15611   
23      0.12624   0.66286    0.21916   1.3553   21.588   0.020227    0.15633   
24      0.29264   0.29252    0.34415    2.327   108.07          0    0.36131   
25     0.079997   0.23967    0.32124   2.4739   8.1087    0.20743   0.069715   
26      0.20817    0.6024    0.47935   2.1883   69.659          0    0.25911   
27      0.26345   0.14318    0.61965   5.3277   198.95    0.55971    0.32142   
28    -0.054623   0.92857  -0.026927  0.94263  -87.724  -0.054623  -0.054623   
29     -0.35884    1.1171   -0.46577  0.46115  -152.21    -1.1752   -0.35884   
...         ...       ...        ...      ...      ...        ...        ...   
6997   0.003802   0.14144    0.44904   4.1748   60.896   0.003802  -0.004791   
6998  -0.018516   0.32886   0.069952    1.257  -29.298          0  -0.018781   
6999    0.02283   0.71132  -0.060759   0.6912  -14.081  -0.048958   0.024774   
7000  -0.000153   0.50582   -0.42127  0.15367  -883.03  -0.000153  -0.004183   
7001   -0.28971    1.1874   -0.46532  0.53814  -223.28   -0.28971   -0.28971   
7002   0.009313   0.61761   -0.22233  0.60119   -62.63          0   0.014544   
7003    0.16773   0.77389    0.16663   1.2414  -28.039          0    0.21742   
7004   -0.33033   0.93266   -0.47693  0.48863  -350.83   -0.33033   -0.33033   
7005    0.04608  0.003824    0.99618    261.5   174.33          0    0.04608   
7006    0.13331   0.16451    0.40084   3.4366   2.8373          0    0.16928   
7007   0.038665  0.071884    0.48884   7.8004   221.01   0.038665   0.045892   
7008   0.001091    0.8516   0.003463   1.0086  -44.467   0.086248   0.001091   
7009  -0.091442    0.7055  -0.047216  0.92568  -7.2952          0  -0.090374   
7010    0.13809    3.3357     -2.364  0.29128  -88.382    -3.3963    0.13809   
7011   0.098271    0.8333   0.000426   1.0005  -43.191          0    0.12838   
7012   0.006404   0.67477  -0.008438  0.98668  -45.599          0   0.009958   
7013   0.037953   0.12239    0.23084    2.886   19.581   0.037953   0.040082   
7014    0.16117  0.072135    0.63649   12.025    178.9          0    0.19986   
7015   0.0194

In [180]:
test = df.replace('?', np.NaN)
test

X1        X2         X3       X4       X5         X6         X7  \
0       0.20055   0.37951    0.39641   2.0472   32.351    0.38825    0.24976   
1       0.20912   0.49988    0.47225   1.9447   14.786          0    0.25834   
2       0.24866   0.69592    0.26713   1.5548  -1.1523          0    0.30906   
3      0.081483   0.30734    0.45879   2.4928   51.952    0.14988   0.092704   
4       0.18732   0.61323     0.2296   1.4063  -7.3128    0.18732    0.18732   
5       0.22822   0.49794    0.35969   1.7502  -47.717          0    0.28139   
6       0.11109   0.64744    0.28971   1.4705   2.5349          0    0.11109   
7       0.53232  0.027059    0.70554   53.954   299.58          0     0.6524   
8       0.00902   0.63202   0.053735   1.1263  -37.842          0   0.014434   
9       0.12408   0.83837    0.14204   1.1694  -91.883          0    0.15328   
10      0.24001   0.44355    0.18835     1.44  -21.165    -0.9319    0.24001   
11    -0.027117   0.11148    0.11989   2.0754  -31.643  -0.084883    -0.0243   
12      0.26669   0.34994    0.61147   3.0243   43.087    0.55983    0.33207   
13     0.067731   0.19885   0.081562   2.9576   90.606    0.21265   0.078063   
14    -0.029182   0.21131    0.45264   7.5746   57.844   0.010387  -0.034653   
15    -0.033801     1.154   -0.20599   0.8215  -74.451   -0.10413  -0.033801   
16      0.27053   0.29913     0.4687   2.5669   73.395    0.72793    0.33619   
17     0.028084   0.24231    0.43224   3.0128   47.935   0.021598   0.039729   
18      0.20393   0.56037    0.13495   1.2408    3.158          0    0.24291   
19      0.20876    0.4965    0.42548    2.019   38.934   0.005436    0.25619   
20      0.11119   0.63174    0.24796        2   58.154    0.24347    0.13909   
21     -0.30505    1.2523   -0.29222  0.71426  -214.91   -0.30505   -0.30505   
22      0.12709    0.5305    0.38069   1.7198  -27.618          0    0.15611   
23      0.12624   0.66286    0.21916   1.3553   21.588   0.020227    0.15633   
24      0.29264   0.29252    0.34415    2.327   108.07          0    0.36131   
25     0.079997   0.23967    0.32124   2.4739   8.1087    0.20743   0.069715   
26      0.20817    0.6024    0.47935   2.1883   69.659          0    0.25911   
27      0.26345   0.14318    0.61965   5.3277   198.95    0.55971    0.32142   
28    -0.054623   0.92857  -0.026927  0.94263  -87.724  -0.054623  -0.054623   
29     -0.35884    1.1171   -0.46577  0.46115  -152.21    -1.1752   -0.35884   
...         ...       ...        ...      ...      ...        ...        ...   
6997   0.003802   0.14144    0.44904   4.1748   60.896   0.003802  -0.004791   
6998  -0.018516   0.32886   0.069952    1.257  -29.298          0  -0.018781   
6999    0.02283   0.71132  -0.060759   0.6912  -14.081  -0.048958   0.024774   
7000  -0.000153   0.50582   -0.42127  0.15367  -883.03  -0.000153  -0.004183   
7001   -0.28971    1.1874   -0.46532  0.53814  -223.28   -0.28971   -0.28971   
7002   0.009313   0.61761   -0.22233  0.60119   -62.63          0   0.014544   
7003    0.16773   0.77389    0.16663   1.2414  -28.039          0    0.21742   
7004   -0.33033   0.93266   -0.47693  0.48863  -350.83   -0.33033   -0.33033   
7005    0.04608  0.003824    0.99618    261.5   174.33          0    0.04608   
7006    0.13331   0.16451    0.40084   3.4366   2.8373          0    0.16928   
7007   0.038665  0.071884    0.48884   7.8004   221.01   0.038665   0.045892   
7008   0.001091    0.8516   0.003463   1.0086  -44.467   0.086248   0.001091   
7009  -0.091442    0.7055  -0.047216  0.92568  -7.2952          0  -0.090374   
7010    0.13809    3.3357     -2.364  0.29128  -88.382    -3.3963    0.13809   
7011   0.098271    0.8333   0.000426   1.0005  -43.191          0    0.12838   
7012   0.006404   0.67477  -0.008438  0.98668  -45.599          0   0.009958   
7013   0.037953   0.12239    0.23084    2.886   19.581   0.037953   0.040082   
7014    0.16117  0.072135    0.63649   12.025    178.9          0    0.19986   
7015   0.0194

In [181]:
#gotta change dem objects to floats man
test.dtypes.eq(object)
c = test.columns[test.dtypes.eq(object)]
test[c] = test[c].apply(pd.to_numeric, errors='coerce', axis=0)
test.dtypes 

X1     float64
X2     float64
X3     float64
X4     float64
X5     float64
X6     float64
X7     float64
X8     float64
X9     float64
X10    float64
X11    float64
X12    float64
X13    float64
X14    float64
X15    float64
X16    float64
X17    float64
X18    float64
X19    float64
X20    float64
X21    float64
X22    float64
X23    float64
X24    float64
X25    float64
X26    float64
X27    float64
X28    float64
X29    float64
X30    float64
        ...   
X36    float64
X37    float64
X38    float64
X39    float64
X40    float64
X41    float64
X42    float64
X43    float64
X44    float64
X45    float64
X46    float64
X47    float64
X48    float64
X49    float64
X50    float64
X51    float64
X52    float64
X53    float64
X54    float64
X55    float64
X56    float64
X57    float64
X58    float64
X59    float64
X60    float64
X61    float64
X62    float64
X63    float64
X64    float64
X65      int64
Length: 65, dtype: object

In [182]:
#filling missing values instead of deleting them
test2=test.fillna(test.mean())


In [183]:
test2

X1        X2        X3         X4        X5        X6        X7  \
0     0.200550  0.379510  0.396410    2.04720   32.3510  0.388250  0.249760   
1     0.209120  0.499880  0.472250    1.94470   14.7860  0.000000  0.258340   
2     0.248660  0.695920  0.267130    1.55480   -1.1523  0.000000  0.309060   
3     0.081483  0.307340  0.458790    2.49280   51.9520  0.149880  0.092704   
4     0.187320  0.613230  0.229600    1.40630   -7.3128  0.187320  0.187320   
5     0.228220  0.497940  0.359690    1.75020  -47.7170  0.000000  0.281390   
6     0.111090  0.647440  0.289710    1.47050    2.5349  0.000000  0.111090   
7     0.532320  0.027059  0.705540   53.95400  299.5800  0.000000  0.652400   
8     0.009020  0.632020  0.053735    1.12630  -37.8420  0.000000  0.014434   
9     0.124080  0.838370  0.142040    1.16940  -91.8830  0.000000  0.153280   
10    0.240010  0.443550  0.188350    1.44000  -21.1650 -0.931900  0.240010   
11   -0.027117  0.111480  0.119890    2.07540  -31.6430 -0.084883 -0.024300   
12    0.266690  0.349940  0.611470    3.02430   43.0870  0.559830  0.332070   
13    0.067731  0.198850  0.081562    2.95760   90.6060  0.212650  0.078063   
14   -0.029182  0.211310  0.452640    7.57460   57.8440  0.010387 -0.034653   
15   -0.033801  1.154000 -0.205990    0.82150  -74.4510 -0.104130 -0.033801   
16    0.270530  0.299130  0.468700    2.56690   73.3950  0.727930  0.336190   
17    0.028084  0.242310  0.432240    3.01280   47.9350  0.021598  0.039729   
18    0.203930  0.560370  0.134950    1.24080    3.1580  0.000000  0.242910   
19    0.208760  0.496500  0.425480    2.01900   38.9340  0.005436  0.256190   
20    0.111190  0.631740  0.247960    2.00000   58.1540  0.243470  0.139090   
21   -0.305050  1.252300 -0.292220    0.71426 -214.9100 -0.305050 -0.305050   
22    0.127090  0.530500  0.380690    1.71980  -27.6180  0.000000  0.156110   
23    0.126240  0.662860  0.219160    1.35530   21.5880  0.020227  0.156330   
24    0.292640  0.292520  0.344150    2.32700  108.0700  0.000000  0.361310   
25    0.079997  0.239670  0.321240    2.47390    8.1087  0.207430  0.069715   
26    0.208170  0.602400  0.479350    2.18830   69.6590  0.000000  0.259110   
27    0.263450  0.143180  0.619650    5.32770  198.9500  0.559710  0.321420   
28   -0.054623  0.928570 -0.026927    0.94263  -87.7240 -0.054623 -0.054623   
29   -0.358840  1.117100 -0.465770    0.46115 -152.2100 -1.175200 -0.358840   
...        ...       ...       ...        ...       ...       ...       ...   
6997  0.003802  0.141440  0.449040    4.17480   60.8960  0.003802 -0.004791   
6998 -0.018516  0.328860  0.069952    1.25700  -29.2980  0.000000 -0.018781   
6999  0.022830  0.711320 -0.060759    0.69120  -14.0810 -0.048958  0.024774   
7000 -0.000153  0.505820 -0.421270    0.15367 -883.0300 -0.000153 -0.004183   
7001 -0.289710  1.187400 -0.465320    0.53814 -223.2800 -0.289710 -0.289710   
7002  0.009313  0.617610 -0.222330    0.60119  -62.6300  0.000000  0.014544   
7003  0.167730  0.773890  0.166630    1.24140  -28.0390  0.000000  0.217420   
7004 -0.330330  0.932660 -0.476930    0.48863 -350.8300 -0.330330 -0.330330   
7005  0.046080  0.003824  0.996180  261.50000  174.3300  0.000000  0.046080   
7006  0.133310  0.164510  0.400840    3.43660    2.8373  0.000000  0.169280   
7007  0.038665  0.071884  0.488840    7.80040  221.0100  0.038665  0.045892   
7008  0.001091  0.851600  0.003463    1.00860  -44.4670  0.086248  0.001091   
7009 -0.091442  0.705500 -0.047216    0.92568   -7.2952  0.000000 -0.090374   
7010  0.138090  3.335700 -2.364000    0.29128  -88.3820 -3.396300  0.138090   
7011  0.098271  0.833300  0.000426    1.00050  -43.1910  0.000000  0.128380   
7012  0.006404  0.674770 -0.008438    0.98668  -45.5990  0.000000  0.009958   
7013  0.037953  0.122390  0.230840    2.88600   19.5810  0.037953  0.040082   
7014  0.161170  0.072135  0.636490   12.02500  178.9000  0.000000  0.199860   
7015  0.019432  0.616330  0.057718    1.10620 -162.8800  0.019

In [184]:
from sklearn import preprocessing

x = test2.values #returns a numpy array
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
test2 = pd.DataFrame(x_scaled)

In [185]:
test2

0         1         2         3         4         5         6   \
0     0.732097  0.141224  0.998633  0.002011  0.733136  0.567704  0.295043   
1     0.732122  0.141459  0.998805  0.001911  0.733131  0.567150  0.295056   
2     0.732234  0.141840  0.998340  0.001528  0.733127  0.567150  0.295135   
3     0.731758  0.141084  0.998774  0.002449  0.733141  0.567364  0.294798   
4     0.732059  0.141679  0.998255  0.001382  0.733125  0.567417  0.294946   
5     0.732176  0.141455  0.998550  0.001720  0.733114  0.567150  0.295092   
6     0.731842  0.141746  0.998391  0.001445  0.733128  0.567150  0.294827   
7     0.733042  0.140538  0.999333  0.053010  0.733208  0.567150  0.295668   
8     0.731552  0.141716  0.997857  0.001107  0.733117  0.567150  0.294677   
9     0.731879  0.142118  0.998057  0.001149  0.733102  0.567150  0.294893   
10    0.732209  0.141349  0.998162  0.001415  0.733121  0.565822  0.295027   
11    0.731449  0.140702  0.998007  0.002039  0.733118  0.567029  0.294617   
12    0.732285  0.141167  0.999120  0.002971  0.733138  0.567948  0.295171   
13    0.731719  0.140872  0.997920  0.002906  0.733151  0.567453  0.294776   
14    0.731443  0.140897  0.998760  0.007442  0.733142  0.567165  0.294601   
15    0.731430  0.142732  0.997268  0.000807  0.733107  0.567002  0.294602   
16    0.732296  0.141068  0.998797  0.002522  0.733147  0.568188  0.295177   
17    0.731606  0.140957  0.998714  0.002960  0.733140  0.567181  0.294716   
18    0.732107  0.141576  0.998041  0.001219  0.733128  0.567150  0.295032   
19    0.732121  0.141452  0.998699  0.001984  0.733137  0.567158  0.295053   
20    0.731843  0.141715  0.998297  0.001965  0.733143  0.567497  0.294871   
21    0.730657  0.142923  0.997073  0.000702  0.733069  0.566716  0.294180   
22    0.731888  0.141518  0.998597  0.001690  0.733119  0.567150  0.294897   
23    0.731886  0.141776  0.998231  0.001332  0.733133  0.567179  0.294897   
24    0.732359  0.141055  0.998514  0.002286  0.733156  0.567150  0.295216   
25    0.731754  0.140952  0.998463  0.002431  0.733129  0.567446  0.294763   
26    0.732119  0.141658  0.998821  0.002150  0.733146  0.567150  0.295057   
27    0.732276  0.140764  0.999139  0.005235  0.733180  0.567948  0.295154   
28    0.731370  0.142293  0.997674  0.000926  0.733103  0.567072  0.294569   
29    0.730504  0.142660  0.996680  0.000453  0.733086  0.565475  0.294097   
...        ...       ...       ...       ...       ...       ...       ...   
6997  0.731537  0.140761  0.998752  0.004102  0.733143  0.567156  0.294647   
6998  0.731473  0.141126  0.997893  0.001235  0.733119  0.567150  0.294625   
6999  0.731591  0.141870  0.997597  0.000679  0.733123  0.567081  0.294693   
7000  0.731526  0.141470  0.996781  0.000151  0.732889  0.567150  0.294648   
7001  0.730701  0.142797  0.996681  0.000529  0.733067  0.566737  0.294204   
7002  0.731553  0.141688  0.997231  0.000591  0.733110  0.567150  0.294677   
7003  0.732004  0.141992  0.998112  0.001220  0.733119  0.567150  0.294992   
7004  0.730585  0.142301  0.996655  0.000480  0.733032  0.566679  0.294141   
7005  0.731657  0.140493  0.999991  0.256927  0.733174  0.567150  0.294726   
7006  0.731906  0.140806  0.998643  0.003376  0.733128  0.567150  0.294918   
7007  0.731636  0.140625  0.998842  0.007664  0.733186  0.567205  0.294726   
7008  0.731529  0.142143  0.997743  0.000991  0.733115  0.567273  0.294656   
7009  0.731266  0.141859  0.997628  0.000909  0.733125  0.567150  0.294514   
7010  0.731919  0.146979  0.992381  0.000286  0.733103  0.562309  0.294869   
7011  0.731806  0.142108  0.997736  0.000983  0.733115  0.567150  0.294854   
7012  0.731544  0.141799  0.997716  0.000969  0.733115  0.567150  0.294670   
7013  0.731634  0.140724  0.998258  0.002836  0.733132  0.567204  0.294717   
7014  0.731985  0.140626  0.999177  0.011815  0.733175  0.567150  0.294965   
7015  0.731581  0.141685  0.997866  0.001087  0.733083  0.567178  0.294667   
7016  0.731591  0.141651  0.997389

In [186]:
#tree classifier


In [187]:
from sklearn.model_selection import train_test_split

In [188]:
#x65 now reffered to 64 after normalizing
X=test2.drop(64,axis=1)

In [189]:
y=test2[64]

In [190]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3)

In [191]:
#DecisionTreeClassifier
from sklearn.tree import DecisionTreeClassifier

In [192]:
dtree = DecisionTreeClassifier(criterion='entropy')

In [193]:
dtree.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [194]:
predictions = dtree.predict(X_test)

In [195]:
from sklearn.metrics import classification_report, confusion_matrix

In [196]:
print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

[[1990   40]
 [  40   39]]


             precision    recall  f1-score   support

        0.0       0.98      0.98      0.98      2030
        1.0       0.49      0.49      0.49        79

avg / total       0.96      0.96      0.96      2109



In [197]:
#regression 
from sklearn.tree import DecisionTreeRegressor

In [198]:
dtree = DecisionTreeRegressor()

In [199]:
dtree.fit(X_train,y_train)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best')

In [200]:
predictions = dtree.predict(X_test)

In [201]:
from sklearn.metrics import classification_report, confusion_matrix

In [202]:
print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

[[1981   49]
 [  37   42]]


             precision    recall  f1-score   support

        0.0       0.98      0.98      0.98      2030
        1.0       0.46      0.53      0.49        79

avg / total       0.96      0.96      0.96      2109



In [203]:
#random forest
from sklearn.ensemble import RandomForestClassifier

In [204]:
model=RandomForestClassifier(n_estimators=10, max_depth=None,min_samples_split=2, random_state=0)

In [205]:
model.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [206]:
predictions = model.predict(X_test)

In [207]:
from sklearn.metrics import classification_report, confusion_matrix

In [208]:
print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

[[2023    7]
 [  51   28]]


             precision    recall  f1-score   support

        0.0       0.98      1.00      0.99      2030
        1.0       0.80      0.35      0.49        79

avg / total       0.97      0.97      0.97      2109



In [209]:
#knn
from sklearn.neighbors.nearest_centroid import NearestCentroid

In [210]:
model=NearestCentroid()

In [211]:
model.fit(X_train,y_train)

NearestCentroid(metric='euclidean', shrink_threshold=None)

In [212]:
predictions = model.predict(X_test)

In [213]:
from sklearn.metrics import classification_report, confusion_matrix

In [214]:
print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

[[1127  903]
 [  40   39]]


             precision    recall  f1-score   support

        0.0       0.97      0.56      0.71      2030
        1.0       0.04      0.49      0.08        79

avg / total       0.93      0.55      0.68      2109



In [215]:
#Probabilistic
from sklearn.naive_bayes import GaussianNB

In [216]:
model = GaussianNB()

In [217]:
model.fit(X_train,y_train)

GaussianNB(priors=None)

In [218]:
predictions = model.predict(X_test)

In [219]:
from sklearn.metrics import classification_report, confusion_matrix

In [220]:
print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

[[  68 1962]
 [   2   77]]


             precision    recall  f1-score   support

        0.0       0.97      0.03      0.06      2030
        1.0       0.04      0.97      0.07        79

avg / total       0.94      0.07      0.07      2109



In [221]:
#SVM's
from sklearn.svm import SVC

In [222]:
model = SVC()

In [223]:
model.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [224]:
predictions = model.predict(X_test)

In [225]:
from sklearn.metrics import classification_report, confusion_matrix

In [226]:
print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

[[2030    0]
 [  79    0]]


             precision    recall  f1-score   support

        0.0       0.96      1.00      0.98      2030
        1.0       0.00      0.00      0.00        79

avg / total       0.93      0.96      0.94      2109



In [249]:
#SGD
from sklearn.linear_model import SGDClassifier

In [250]:
clf = SGDClassifier(loss="hinge", penalty="l2")
clf.fit(X_train,y_train)

SGDClassifier(alpha=0.0001, average=False, class_weight=None, epsilon=0.1,
       eta0=0.0, fit_intercept=True, l1_ratio=0.15,
       learning_rate='optimal', loss='hinge', max_iter=None, n_iter=None,
       n_jobs=1, penalty='l2', power_t=0.5, random_state=None,
       shuffle=True, tol=None, verbose=0, warm_start=False)

In [251]:
predictions=clf.predict(X_test)

In [252]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

[[2030    0]
 [  79    0]]


             precision    recall  f1-score   support

        0.0       0.96      1.00      0.98      2030
        1.0       0.00      0.00      0.00        79

avg / total       0.93      0.96      0.94      2109



In [253]:
#neural networks
from sklearn.neural_network import MLPClassifier

In [254]:
clf = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1)

In [255]:
clf.fit(X_train,y_train)

MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(5, 2), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='lbfgs', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)

In [256]:
predictions=clf.predict(X_test)

In [257]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

[[2030    0]
 [  79    0]]


             precision    recall  f1-score   support

        0.0       0.96      1.00      0.98      2030
        1.0       0.00      0.00      0.00        79

avg / total       0.93      0.96      0.94      2109



In [258]:
#Linear SVC

In [260]:
from sklearn.svm import LinearSVC
clf = LinearSVC(random_state=0)
clf.fit(X_train, y_train)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=0, tol=0.0001,
     verbose=0)

In [261]:
predictions=clf.predict(X_test)

In [262]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

[[2030    0]
 [  79    0]]


             precision    recall  f1-score   support

        0.0       0.96      1.00      0.98      2030
        1.0       0.00      0.00      0.00        79

avg / total       0.93      0.96      0.94      2109



In [286]:
#Kernel
test.np.reshape(999,1)

AttributeError: 'DataFrame' object has no attribute 'np'

In [277]:
from sklearn.kernel_approximation import RBFSampler
from sklearn.linear_model import SGDClassifier
rbf_feature = RBFSampler(gamma=1, random_state=1)
X_features = rbf_feature.fit_transform(X_train)
clf = SGDClassifier()   
clf.fit(X_features, y_train)

clf.score(X_features, y)

ValueError: Found input variables with inconsistent numbers of samples: [7027, 4918]

In [282]:
test2.dtypes

0     float64
1     float64
2     float64
3     float64
4     float64
5     float64
6     float64
7     float64
8     float64
9     float64
10    float64
11    float64
12    float64
13    float64
14    float64
15    float64
16    float64
17    float64
18    float64
19    float64
20    float64
21    float64
22    float64
23    float64
24    float64
25    float64
26    float64
27    float64
28    float64
29    float64
       ...   
35    float64
36    float64
37    float64
38    float64
39    float64
40    float64
41    float64
42    float64
43    float64
44    float64
45    float64
46    float64
47    float64
48    float64
49    float64
50    float64
51    float64
52    float64
53    float64
54    float64
55    float64
56    float64
57    float64
58    float64
59    float64
60    float64
61    float64
62    float64
63    float64
64    float64
Length: 65, dtype: object