In [61]:
import csv
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [62]:
bc = "companydata.csv"
df = pd.read_csv(bc, header = 0)
df

X1        X2         X3       X4       X5         X6         X7  \
0       0.20055   0.37951    0.39641   2.0472   32.351    0.38825    0.24976   
1       0.20912   0.49988    0.47225   1.9447   14.786          0    0.25834   
2       0.24866   0.69592    0.26713   1.5548  -1.1523          0    0.30906   
3      0.081483   0.30734    0.45879   2.4928   51.952    0.14988   0.092704   
4       0.18732   0.61323     0.2296   1.4063  -7.3128    0.18732    0.18732   
5       0.22822   0.49794    0.35969   1.7502  -47.717          0    0.28139   
6       0.11109   0.64744    0.28971   1.4705   2.5349          0    0.11109   
7       0.53232  0.027059    0.70554   53.954   299.58          0     0.6524   
8       0.00902   0.63202   0.053735   1.1263  -37.842          0   0.014434   
9       0.12408   0.83837    0.14204   1.1694  -91.883          0    0.15328   
10      0.24001   0.44355    0.18835     1.44  -21.165    -0.9319    0.24001   
11    -0.027117   0.11148    0.11989   2.0754  -31.643  -0.084883    -0.0243   
12      0.26669   0.34994    0.61147   3.0243   43.087    0.55983    0.33207   
13     0.067731   0.19885   0.081562   2.9576   90.606    0.21265   0.078063   
14    -0.029182   0.21131    0.45264   7.5746   57.844   0.010387  -0.034653   
15    -0.033801     1.154   -0.20599   0.8215  -74.451   -0.10413  -0.033801   
16      0.27053   0.29913     0.4687   2.5669   73.395    0.72793    0.33619   
17     0.028084   0.24231    0.43224   3.0128   47.935   0.021598   0.039729   
18      0.20393   0.56037    0.13495   1.2408    3.158          0    0.24291   
19      0.20876    0.4965    0.42548    2.019   38.934   0.005436    0.25619   
20      0.11119   0.63174    0.24796        2   58.154    0.24347    0.13909   
21     -0.30505    1.2523   -0.29222  0.71426  -214.91   -0.30505   -0.30505   
22      0.12709    0.5305    0.38069   1.7198  -27.618          0    0.15611   
23      0.12624   0.66286    0.21916   1.3553   21.588   0.020227    0.15633   
24      0.29264   0.29252    0.34415    2.327   108.07          0    0.36131   
25     0.079997   0.23967    0.32124   2.4739   8.1087    0.20743   0.069715   
26      0.20817    0.6024    0.47935   2.1883   69.659          0    0.25911   
27      0.26345   0.14318    0.61965   5.3277   198.95    0.55971    0.32142   
28    -0.054623   0.92857  -0.026927  0.94263  -87.724  -0.054623  -0.054623   
29     -0.35884    1.1171   -0.46577  0.46115  -152.21    -1.1752   -0.35884   
...         ...       ...        ...      ...      ...        ...        ...   
6997   0.003802   0.14144    0.44904   4.1748   60.896   0.003802  -0.004791   
6998  -0.018516   0.32886   0.069952    1.257  -29.298          0  -0.018781   
6999    0.02283   0.71132  -0.060759   0.6912  -14.081  -0.048958   0.024774   
7000  -0.000153   0.50582   -0.42127  0.15367  -883.03  -0.000153  -0.004183   
7001   -0.28971    1.1874   -0.46532  0.53814  -223.28   -0.28971   -0.28971   
7002   0.009313   0.61761   -0.22233  0.60119   -62.63          0   0.014544   
7003    0.16773   0.77389    0.16663   1.2414  -28.039          0    0.21742   
7004   -0.33033   0.93266   -0.47693  0.48863  -350.83   -0.33033   -0.33033   
7005    0.04608  0.003824    0.99618    261.5   174.33          0    0.04608   
7006    0.13331   0.16451    0.40084   3.4366   2.8373          0    0.16928   
7007   0.038665  0.071884    0.48884   7.8004   221.01   0.038665   0.045892   
7008   0.001091    0.8516   0.003463   1.0086  -44.467   0.086248   0.001091   
7009  -0.091442    0.7055  -0.047216  0.92568  -7.2952          0  -0.090374   
7010    0.13809    3.3357     -2.364  0.29128  -88.382    -3.3963    0.13809   
7011   0.098271    0.8333   0.000426   1.0005  -43.191          0    0.12838   
7012   0.006404   0.67477  -0.008438  0.98668  -45.599          0   0.009958   
7013   0.037953   0.12239    0.23084    2.886   19.581   0.037953   0.040082   
7014    0.16117  0.072135    0.63649   12.025    178.9          0    0.19986   
7015   0.0194

In [63]:
test = df.replace('?', np.NaN)
test

X1        X2         X3       X4       X5         X6         X7  \
0       0.20055   0.37951    0.39641   2.0472   32.351    0.38825    0.24976   
1       0.20912   0.49988    0.47225   1.9447   14.786          0    0.25834   
2       0.24866   0.69592    0.26713   1.5548  -1.1523          0    0.30906   
3      0.081483   0.30734    0.45879   2.4928   51.952    0.14988   0.092704   
4       0.18732   0.61323     0.2296   1.4063  -7.3128    0.18732    0.18732   
5       0.22822   0.49794    0.35969   1.7502  -47.717          0    0.28139   
6       0.11109   0.64744    0.28971   1.4705   2.5349          0    0.11109   
7       0.53232  0.027059    0.70554   53.954   299.58          0     0.6524   
8       0.00902   0.63202   0.053735   1.1263  -37.842          0   0.014434   
9       0.12408   0.83837    0.14204   1.1694  -91.883          0    0.15328   
10      0.24001   0.44355    0.18835     1.44  -21.165    -0.9319    0.24001   
11    -0.027117   0.11148    0.11989   2.0754  -31.643  -0.084883    -0.0243   
12      0.26669   0.34994    0.61147   3.0243   43.087    0.55983    0.33207   
13     0.067731   0.19885   0.081562   2.9576   90.606    0.21265   0.078063   
14    -0.029182   0.21131    0.45264   7.5746   57.844   0.010387  -0.034653   
15    -0.033801     1.154   -0.20599   0.8215  -74.451   -0.10413  -0.033801   
16      0.27053   0.29913     0.4687   2.5669   73.395    0.72793    0.33619   
17     0.028084   0.24231    0.43224   3.0128   47.935   0.021598   0.039729   
18      0.20393   0.56037    0.13495   1.2408    3.158          0    0.24291   
19      0.20876    0.4965    0.42548    2.019   38.934   0.005436    0.25619   
20      0.11119   0.63174    0.24796        2   58.154    0.24347    0.13909   
21     -0.30505    1.2523   -0.29222  0.71426  -214.91   -0.30505   -0.30505   
22      0.12709    0.5305    0.38069   1.7198  -27.618          0    0.15611   
23      0.12624   0.66286    0.21916   1.3553   21.588   0.020227    0.15633   
24      0.29264   0.29252    0.34415    2.327   108.07          0    0.36131   
25     0.079997   0.23967    0.32124   2.4739   8.1087    0.20743   0.069715   
26      0.20817    0.6024    0.47935   2.1883   69.659          0    0.25911   
27      0.26345   0.14318    0.61965   5.3277   198.95    0.55971    0.32142   
28    -0.054623   0.92857  -0.026927  0.94263  -87.724  -0.054623  -0.054623   
29     -0.35884    1.1171   -0.46577  0.46115  -152.21    -1.1752   -0.35884   
...         ...       ...        ...      ...      ...        ...        ...   
6997   0.003802   0.14144    0.44904   4.1748   60.896   0.003802  -0.004791   
6998  -0.018516   0.32886   0.069952    1.257  -29.298          0  -0.018781   
6999    0.02283   0.71132  -0.060759   0.6912  -14.081  -0.048958   0.024774   
7000  -0.000153   0.50582   -0.42127  0.15367  -883.03  -0.000153  -0.004183   
7001   -0.28971    1.1874   -0.46532  0.53814  -223.28   -0.28971   -0.28971   
7002   0.009313   0.61761   -0.22233  0.60119   -62.63          0   0.014544   
7003    0.16773   0.77389    0.16663   1.2414  -28.039          0    0.21742   
7004   -0.33033   0.93266   -0.47693  0.48863  -350.83   -0.33033   -0.33033   
7005    0.04608  0.003824    0.99618    261.5   174.33          0    0.04608   
7006    0.13331   0.16451    0.40084   3.4366   2.8373          0    0.16928   
7007   0.038665  0.071884    0.48884   7.8004   221.01   0.038665   0.045892   
7008   0.001091    0.8516   0.003463   1.0086  -44.467   0.086248   0.001091   
7009  -0.091442    0.7055  -0.047216  0.92568  -7.2952          0  -0.090374   
7010    0.13809    3.3357     -2.364  0.29128  -88.382    -3.3963    0.13809   
7011   0.098271    0.8333   0.000426   1.0005  -43.191          0    0.12838   
7012   0.006404   0.67477  -0.008438  0.98668  -45.599          0   0.009958   
7013   0.037953   0.12239    0.23084    2.886   19.581   0.037953   0.040082   
7014    0.16117  0.072135    0.63649   12.025    178.9          0    0.19986   
7015   0.0194

In [64]:
#gotta change dem objects to floats man
test.dtypes.eq(object)
c = test.columns[test.dtypes.eq(object)]
test[c] = test[c].apply(pd.to_numeric, errors='coerce', axis=0)
test.dtypes 

X1     float64
X2     float64
X3     float64
X4     float64
X5     float64
X6     float64
X7     float64
X8     float64
X9     float64
X10    float64
X11    float64
X12    float64
X13    float64
X14    float64
X15    float64
X16    float64
X17    float64
X18    float64
X19    float64
X20    float64
X21    float64
X22    float64
X23    float64
X24    float64
X25    float64
X26    float64
X27    float64
X28    float64
X29    float64
X30    float64
        ...   
X36    float64
X37    float64
X38    float64
X39    float64
X40    float64
X41    float64
X42    float64
X43    float64
X44    float64
X45    float64
X46    float64
X47    float64
X48    float64
X49    float64
X50    float64
X51    float64
X52    float64
X53    float64
X54    float64
X55    float64
X56    float64
X57    float64
X58    float64
X59    float64
X60    float64
X61    float64
X62    float64
X63    float64
X64    float64
X65      int64
Length: 65, dtype: object

In [65]:
#filling missing values instead of deleting them
test2=test.fillna(test.mean())


In [66]:
from sklearn.model_selection import train_test_split

In [75]:
from sklearn.preprocessing import Normalizer
#a = test2.values #returns a numpy array
scaler = Normalizer().fit(X)
x_scaled = scaler.transform(X)
X= pd.DataFrame(x_scaled)
X

0         1             2         3         4             5   \
0     5.751512e-07  0.000001  1.136852e-06  0.000006  0.000093  1.113450e-06   
1     8.601955e-05  0.000206  1.942556e-04  0.000800  0.006082  0.000000e+00   
2     3.890959e-05  0.000109  4.179972e-05  0.000243 -0.000180  0.000000e+00   
3     3.961637e-06  0.000015  2.230600e-05  0.000121  0.002526  7.287044e-06   
4     5.520971e-05  0.000181  6.767110e-05  0.000414 -0.002155  5.520971e-05   
5     2.984470e-05  0.000065  4.703725e-05  0.000229 -0.006240  0.000000e+00   
6     7.294304e-05  0.000425  1.902271e-04  0.000966  0.001664  0.000000e+00   
7     4.311661e-05  0.000002  5.714701e-05  0.004370  0.024265  0.000000e+00   
8     2.026706e-06  0.000142  1.207373e-05  0.000253 -0.008503  0.000000e+00   
9     5.656845e-05  0.000382  6.475647e-05  0.000533 -0.041890  0.000000e+00   
10    5.876616e-04  0.001086  4.611727e-04  0.003526 -0.051822 -2.281746e-03   
11   -1.710134e-05  0.000070  7.560866e-05  0.001309 -0.019956 -5.353149e-05   
12    4.980259e-05  0.000065  1.141880e-04  0.000565  0.008046  1.045445e-04   
13    4.466966e-06  0.000013  5.379142e-06  0.000195  0.005976  1.402460e-05   
14   -7.003502e-07  0.000005  1.086308e-05  0.000182  0.001388  2.492817e-07   
15   -5.793604e-07  0.000020 -3.530737e-06  0.000014 -0.001276 -1.784823e-06   
16    2.630198e-05  0.000029  4.556884e-05  0.000250  0.007136  7.077220e-05   
17    2.179558e-06  0.000019  3.354552e-05  0.000234  0.003720  1.676189e-06   
18    1.898475e-04  0.000522  1.256310e-04  0.001155  0.002940  0.000000e+00   
19    3.441361e-05  0.000082  7.013942e-05  0.000333  0.006418  8.961123e-07   
20    4.591905e-05  0.000261  1.024021e-04  0.000826  0.024016  1.005478e-04   
21   -3.146597e-05  0.000129 -3.014255e-05  0.000074 -0.022168 -3.146597e-05   
22    9.694579e-05  0.000405  2.903949e-04  0.001312 -0.021067  0.000000e+00   
23    6.368141e-05  0.000334  1.105546e-04  0.000684  0.010890  1.020345e-05   
24    6.235142e-05  0.000062  7.332642e-05  0.000496  0.023026  0.000000e+00   
25    9.713469e-06  0.000029  3.900590e-05  0.000300  0.000985  2.518676e-05   
26    9.196026e-06  0.000027  2.117555e-05  0.000097  0.003077  0.000000e+00   
27    1.317497e-05  0.000007  3.098832e-05  0.000266  0.009949  2.799076e-05   
28   -2.577208e-06  0.000044 -1.270463e-06  0.000044 -0.004139 -2.577208e-06   
29   -6.342316e-05  0.000197 -8.232250e-05  0.000082 -0.026902 -2.077107e-04   
...            ...       ...           ...       ...       ...           ...   
6997  7.806450e-07  0.000029  9.219906e-05  0.000857  0.012503  7.806450e-07   
6998 -4.654067e-06  0.000083  1.758270e-05  0.000316 -0.007364  0.000000e+00   
6999  7.507779e-06  0.000234 -1.998095e-05  0.000227 -0.004631 -1.610013e-05   
7000 -3.780602e-09  0.000012 -1.040950e-05  0.000004 -0.021820 -3.780602e-09   
7001 -7.141671e-05  0.000293 -1.147065e-04  0.000133 -0.055041 -7.141671e-05   
7002  2.653999e-06  0.000176 -6.335912e-05  0.000171 -0.017848  0.000000e+00   
7003  1.197740e-04  0.000553  1.189885e-04  0.000886 -0.020022  0.000000e+00   
7004 -3.704811e-05  0.000105 -5.349002e-05  0.000055 -0.039347 -3.704811e-05   
7005  2.543374e-05  0.000002  5.498390e-04  0.144334  0.096221  0.000000e+00   
7006  2.504762e-04  0.000309  7.531383e-04  0.006457  0.005331  0.000000e+00   
7007  6.478678e-06  0.000012  8.190966e-05  0.001307  0.037032  6.478678e-06   
7008  9.371241e-08  0.000073  2.974575e-07  0.000087 -0.003820  7.408348e-06   
7009 -1.197824e-05  0.000092 -6.184953e-06  0.000121 -0.000956  0.000000e+00   
7010  1.563027e-05  0.000378 -2.675788e-04  0.000033 -0.010004 -3.844237e-04   
7011  2.476322e-05  0.000210  1.073473e-07  0.000252 -0.010884  0.000000e+00   
7012  2.588817e-07  0.000027 -3.411062e-07  0.000040 -0.001843  0.000000e+00   
7013  2.080830e-05  0.000067  1.265615e-04  0.001582  0.010736  2.080830e-05   
7014  2.588192e-05  0.000012  1.022125e-04  0.001931  0.028729  0.000000e+00   
7015  4.418919e-

In [78]:
y=test2['X65']

In [79]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3)

In [80]:
#DecisionTreeClassifier
from sklearn.tree import DecisionTreeClassifier

In [81]:
dtree = DecisionTreeClassifier(criterion='entropy')
dtree.fit(X_train,y_train)
predictions = dtree.predict(X_test)

In [82]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import metrics

print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))
print('\n')
print(metrics.accuracy_score(y_test,predictions))

[[1978   56]
 [  36   39]]


             precision    recall  f1-score   support

          0       0.98      0.97      0.98      2034
          1       0.41      0.52      0.46        75

avg / total       0.96      0.96      0.96      2109



0.956377430062


In [83]:
#regression 
from sklearn.tree import DecisionTreeRegressor




In [84]:
dtree = DecisionTreeRegressor()

In [85]:
dtree.fit(X_train,y_train)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best')

In [86]:
predictions = dtree.predict(X_test)

In [87]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import metrics



In [88]:
print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

[[1983   51]
 [  44   31]]


             precision    recall  f1-score   support

          0       0.98      0.97      0.98      2034
          1       0.38      0.41      0.39        75

avg / total       0.96      0.95      0.96      2109



In [89]:
#random forest
from sklearn.ensemble import RandomForestClassifier

In [90]:
model=RandomForestClassifier(n_estimators=10, max_depth=None,min_samples_split=2, random_state=0)

In [91]:
model.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [92]:
predictions = model.predict(X_test)

In [93]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import metrics

In [94]:
print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))
print('\n')
print(metrics.accuracy_score(y_test,predictions))

[[2030    4]
 [  59   16]]


             precision    recall  f1-score   support

          0       0.97      1.00      0.98      2034
          1       0.80      0.21      0.34        75

avg / total       0.97      0.97      0.96      2109



0.97012802276


In [101]:
#knn
from sklearn.neighbors.nearest_centroid import NearestCentroid

In [132]:
model=NearestCentroid()

In [133]:
model.fit(X_train,y_train)

NearestCentroid(metric='euclidean', shrink_threshold=None)

In [134]:
predictions = model.predict(X_test)

In [135]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import metrics

print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))
print('\n')
print(metrics.accuracy_score(y_test,predictions))

[[1316  718]
 [  28   47]]


             precision    recall  f1-score   support

          0       0.98      0.65      0.78      2034
          1       0.06      0.63      0.11        75

avg / total       0.95      0.65      0.76      2109



0.646277856804


In [136]:
#Probabilistic
from sklearn.naive_bayes import GaussianNB

In [107]:
model = GaussianNB()

In [108]:
model.fit(X_train,y_train)

GaussianNB(priors=None)

In [109]:
predictions = model.predict(X_test)

In [110]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import metrics

print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))
print('\n')
print(metrics.accuracy_score(y_test,predictions))

[[ 267 1767]
 [   8   67]]


             precision    recall  f1-score   support

          0       0.97      0.13      0.23      2034
          1       0.04      0.89      0.07        75

avg / total       0.94      0.16      0.23      2109



0.158368895211


In [111]:
#SVM's
from sklearn.svm import SVC

In [112]:
model = SVC()

In [113]:
model.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [114]:
predictions = model.predict(X_test)

In [115]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import metrics

print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))
print('\n')
print(metrics.accuracy_score(y_test,predictions))

[[2034    0]
 [  75    0]]


             precision    recall  f1-score   support

          0       0.96      1.00      0.98      2034
          1       0.00      0.00      0.00        75

avg / total       0.93      0.96      0.95      2109



0.964438122333


/home/ven/Venenv/local/lib/python2.7/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [116]:
#SGD
from sklearn.linear_model import SGDClassifier

In [118]:
clf = SGDClassifier(loss="hinge", penalty="l2")
clf.fit(X_train,y_train)

SGDClassifier(alpha=0.0001, average=False, class_weight=None, epsilon=0.1,
       eta0=0.0, fit_intercept=True, l1_ratio=0.15,
       learning_rate='optimal', loss='hinge', max_iter=None, n_iter=None,
       n_jobs=1, penalty='l2', power_t=0.5, random_state=None,
       shuffle=True, tol=None, verbose=0, warm_start=False)

In [119]:
predictions=clf.predict(X_test)

In [120]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import metrics
print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))
print('\n')
print(metrics.accuracy_score(y_test,predictions))

[[2034    0]
 [  75    0]]


             precision    recall  f1-score   support

          0       0.96      1.00      0.98      2034
          1       0.00      0.00      0.00        75

avg / total       0.93      0.96      0.95      2109



0.964438122333


In [121]:
#neural networks
from sklearn.neural_network import MLPClassifier

In [122]:
clf.fit(X_train,y_train)

SGDClassifier(alpha=0.0001, average=False, class_weight=None, epsilon=0.1,
       eta0=0.0, fit_intercept=True, l1_ratio=0.15,
       learning_rate='optimal', loss='hinge', max_iter=None, n_iter=None,
       n_jobs=1, penalty='l2', power_t=0.5, random_state=None,
       shuffle=True, tol=None, verbose=0, warm_start=False)

In [123]:
predictions=clf.predict(X_test)

In [124]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import metrics
print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))
print('\n')
print(metrics.accuracy_score(y_test,predictions))

[[2034    0]
 [  75    0]]


             precision    recall  f1-score   support

          0       0.96      1.00      0.98      2034
          1       0.00      0.00      0.00        75

avg / total       0.93      0.96      0.95      2109



0.964438122333


In [125]:
#Linear SVC
from sklearn.svm import LinearSVC
clf = LinearSVC(random_state=0)
clf.fit(X_train, y_train)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=0, tol=0.0001,
     verbose=0)

In [126]:
predictions=clf.predict(X_test)

In [127]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import metrics
print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))
print('\n')
print(metrics.accuracy_score(y_test,predictions))

[[2034    0]
 [  75    0]]


             precision    recall  f1-score   support

          0       0.96      1.00      0.98      2034
          1       0.00      0.00      0.00        75

avg / total       0.93      0.96      0.95      2109



0.964438122333
